### ISSUE TITLE
Simple request :)

### ISSUE THREAD

**Issue by hyp3ractive** [Henrik-3/unofficial-valorant-api#12]
Hey;

Can you add functionality to get leaderboard rank based on user?
Usage example - https://api.henrikdev.xyz/valorant/v1/leaderboard/na/{name}/{tag}
Thanks! Love the work so far

**Comment by Henrik-3** [comment]
Hey @hyp3ractive,
I kinda changed your request by not creating a whole new endpoint, but adding the option to add queries.

You can now filter by a name by using the following URL:
- https://api.henrikdev.xyz/valorant/v1/leaderboard/eu?name=NAME-HEREtag=TAG-HERE
- Query name and tag needed, otherwise it returns 400
- When user is not on leaderbaord it returns 404

Example:
https://api.henrikdev.xyz/valorant/v1/leaderboard/eu?name=al0rante&tag=al0
