### ISSUE TITLE
MMR from puuid vs name/tag

### ISSUE THREAD

**Issue by p0thi** [Henrik-3/unofficial-valorant-api#23]
Hello, I wonder, what the requirements for the mmr by puuid are (I believe ranked max 20 games in the past?) compared to the mmr by username and tag.
Because for some users it is possible for me to get the mmr with the username and tag, but not with the puuid.

**Comment by Henrik-3** [comment]
Hey @p0thi, sorry for the late response, got vacinated and was a bit ill. For the MMR by name and tag i implemented a new way to fetch MMR, which seems to be a working solution compared to the puuid one. And yeah u right, for the bypuuid endpoint there was the old system with the 20 matches.

Since about 5min, the bypuuid endpoint uses the same system as the name/tag endpoint, so results should be similar now.

Henrik

**Comment by p0thi** [comment]
Nice to hear! Thank you!
What is the limitation now for the mmr to be returned by the endpoints. Is it still a competetive match in the last 20 played games?

**Comment by Henrik-3** [comment]
We can't really evaluate how many played games are now needed to display, but we think it's based on the match history. A normal match history normally contains around 70-90 matches, but some players have less in their history. Why this is the case, we don't know :C

**Comment by p0thi** [comment]
Alright. Thanks for the information :)
