### ISSUE TITLE
MMR History

### ISSUE THREAD

**Issue by Y-Tian** [Henrik-3/unofficial-valorant-api#42]
Thank you for your work on this API!

For the MMR History endpoint: `GET /valorant/v1/mmr-history/:region/:name/:tag`, it only returns a maximum of 10 results. Is it possible to increase this number?

**Comment by Henrik-3** [comment]
When my exams are over (Wednesday) i will try to take a look, i actually don't know right now

**Comment by Henrik-3** [comment]
Hey, the endpoint should now return **up to** 20 entries, based on how much ranked this player has played

**Comment by Y-Tian** [comment]
Thanks for the update! Is it possible to make this number even larger/dynamic and trade off the speed of the query? Aka pass in the number of requested results as a field in the query?

I’m looking to create a graph of mmr history and this feature would be very useful!

**Comment by Henrik-3** [comment]
Well larger is a bit difficult since then i have to do multiple requests, in theory it should be possible, but i guess i wont implement it because the competitve history doesn't last that long and no one (exept radiants and immortals i guess) play enough competitive for this (i play that came casualy and i have right now 19 entries).

You probably have to do some tracking by yourself then :C
