### ISSUE TITLE
Round's kill events damage weapon name, and assets are null for chamber's abilities (sheriff)?

### ISSUE THREAD

**Issue by M-U-X** [Henrik-3/unofficial-valorant-api#45]
Round's kill events damage weapon name, and assets are null for chamber's abilities  (at least sheriff like weapon), is that by default on riots end, or not implements yet? example match id "80ad1b93-e483-46bb-ac6b-e694efcf6d63" rounds[0].player_stats[5].kill_events[0]

**Comment by Henrik-3** [comment]
This is an issue on my end, let me explain. For always up to date data i use in many parts of my code https://valorant-api.com/ to get metadata or other essential data (like current maps, weapons, agents etc). https://valorant-api.com/v1/weapons for example just have the real weapons, so the API will return null because chambers weapons are not "real" weapons.

I see what can i do to fix that, no ETA tho

**Comment by Henrik-3** [comment]
match v4 now supports also abilities
